<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="yuri-PC" name="Feeder - upload a private key test" tests="1" failures="1" timestamp="4 Aug 2016 21:29:28 GMT" time="0.218" errors="0">
  <testcase name="uploadPrivateKeyToFeeder" time="0.021" classname="com.zixi.testing.FeederPostKeyTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [{&amp;quot;server&amp;quot;:{&amp;quot;key_present&amp;quot;:1,&amp;quot;host&amp;quot;:&amp;quot;10.7.0.66&amp;quot;,&amp;quot;ssh_port&amp;quot;:22,&amp;quot;user&amp;quot;:&amp;quot;root&amp;quot;,&amp;quot;key&amp;quot;:&amp;quot;/zixi9/zixi_feeder-centos7/ssh_tunnel.key&amp;quot;},&amp;quot;tunnels&amp;quot;:[{&amp;quot;target_ip&amp;quot;:&amp;quot;127.0.0.1&amp;quot;,&amp;quot;target_port&amp;quot;:0,&amp;quot;remote_port&amp;quot;:9933,&amp;quot;active&amp;quot;:1,&amp;quot;error&amp;quot;:&amp;quot;&amp;quot;}]}]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [{"server":{"key_present":1,"host":"10.7.0.66","ssh_port":22,"user":"root","key":"/zixi9/zixi_feeder-centos7/ssh_tunnel.key"},"tunnels":[{"target_ip":"127.0.0.1","target_port":0,"remote_port":9933,"active":1,"error":""}]}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.zixi.testing.FeederPostKeyTest.uploadPrivateKeyToFeeder(FeederPostKeyTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- uploadPrivateKeyToFeeder -->
</testsuite> <!-- Feeder - upload a private key test -->
