<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yuri-PC" name="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest" tests="6" failures="1" timestamp="12 Sep 2016 11:06:49 GMT" time="12.874" errors="1">
  <testcase name="broadcasterMultiplePullInCreation" time="1.951" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest"/>
  <testcase name="broadcasterMultiplePullInCreation" time="1.890" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest.broadcasterMultiplePullInCreation(FeederBroadcasterBondingMultipleThreeLinkTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- broadcasterMultiplePullInCreation -->
  <testcase name="broadcasterMultiplePullInCreation" time="2.003" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest"/>
  <testcase name="broadcasterMultiplePullInCreation" time="1.069" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest">
    <error type="com.zixi.tools.BroadcasterInitialSecuredLogin$1" message="Loggin parameters are empty.">
      <![CDATA[com.zixi.tools.BroadcasterInitialSecuredLogin$1: Loggin parameters are empty.
	at com.zixi.tools.BroadcasterInitialSecuredLogin.sendGet(BroadcasterInitialSecuredLogin.java:85)
	at com.zixi.drivers.ProductAboutDriver.getBroadcasterVersion(ProductAboutDriver.java:10)
	at com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest.broadcasterMultiplePullInCreation(FeederBroadcasterBondingMultipleThreeLinkTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- broadcasterMultiplePullInCreation -->
  <testcase name="broadcasterMultiplePullInCreation" time="4.037" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest"/>
  <testcase name="broadcasterMultiplePullInCreation" time="1.924" classname="com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest"/>
</testsuite> <!-- com.zixi.load.testing.FeederBroadcasterBondingMultipleThreeLinkTest -->
